FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o main main.go

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/main ./

RUN apk add --no-cache ca-certificates tzdata

EXPOSE 8083

CMD ["./main"]