FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY API1 ./API1
COPY API2 ./API2

WORKDIR /src/API1
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o api1 main.go

WORKDIR /src/API2
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o api2 main.go

FROM alpine:3.22

RUN apk add --no-cache ca-certificates tzdata bash

WORKDIR /app

COPY --from=builder /src/API1/api1 ./api1
COPY --from=builder /src/API2/api2 ./api2

EXPOSE 8080 8081

COPY start.sh ./start.sh
RUN chmod +x start.sh

CMD ["./start.sh"]